import { CandidateAction, DecisionContext, NeedUrgencyLevel } from '@genesis/shared';
import { UtilityWeights } from '../UtilityWeights';

export class NeedUtilityEvaluator {
  public evaluate(action: CandidateAction, context: DecisionContext): number {
    // If this action was not generated by a Need (e.g. SCHEDULE), return 0
    // Wait, CandidateAction has `source` which corresponds to needType or SCHEDULE.
    const triggeredNeed = context.perception?.self?.vitalState // wait, we can look at the candidate action's source and match it to the context need.
    // Actually, Phase 4.3 CandidateActionSet has `triggeredNeeds`. But `evaluate` only receives context and action.
    // We can calculate urgency dynamically or pass `CandidateActionSet` into `evaluate`.
    // Let's rely on the ActionType or the `source` string.
    
    let baseUrgency = 0;
    let level = NeedUrgencyLevel.MODERATE;

    switch (action.source) {
      case 'HUNGER':
        baseUrgency = context.vitalState.hunger;
        break;
      case 'THIRST':
        baseUrgency = context.vitalState.thirst;
        break;
      case 'ENERGY':
        baseUrgency = 100 - context.vitalState.energy;
        break;
      case 'HEALTH':
        baseUrgency = 100 - context.vitalState.health;
        break;
      default:
        return 0; // Not a need-driven action
    }

    baseUrgency = Math.max(0, Math.min(100, baseUrgency));
    
    if (baseUrgency <= 20) level = NeedUrgencyLevel.VERY_LOW;
    else if (baseUrgency <= 40) level = NeedUrgencyLevel.LOW;
    else if (baseUrgency <= 60) level = NeedUrgencyLevel.MODERATE;
    else if (baseUrgency <= 80) level = NeedUrgencyLevel.HIGH;
    else level = NeedUrgencyLevel.CRITICAL;

    let multiplier = 1.0;
    switch (level) {
      case NeedUrgencyLevel.CRITICAL: multiplier = UtilityWeights.CRITICAL_NEED_MULTIPLIER; break;
      case NeedUrgencyLevel.HIGH: multiplier = UtilityWeights.HIGH_NEED_MULTIPLIER; break;
      case NeedUrgencyLevel.MODERATE: multiplier = UtilityWeights.MODERATE_NEED_MULTIPLIER; break;
      case NeedUrgencyLevel.LOW: multiplier = UtilityWeights.LOW_NEED_MULTIPLIER; break;
      case NeedUrgencyLevel.VERY_LOW: multiplier = UtilityWeights.VERY_LOW_NEED_MULTIPLIER; break;
    }

    return baseUrgency * multiplier;
  }
}
