import { persistenceService } from './src/services/persistence.service';
import { worldService } from './src/services/world.service';
import { citizenService } from './src/services/citizen.service';
import { supplyService } from './src/services/supply.service';
import { environmentService } from './src/services/environment.service';
import { resourceService } from './src/services/resource.service';
import { spatialService } from './src/services/spatial.service';
import { decisionService } from './src/services/decision.service';
import { perceptionService } from './src/services/perception.service';
import { marketService } from './src/services/market.service';
import { financeService } from './src/services/finance.service';
import { bankingService } from './src/services/banking.service';
import { timeService } from './src/services/time.service';

import { prisma } from './src/repositories/prisma';
import { ActionType, ActionState, MovementState, TransactionType, CitizenGender, CitizenStatus } from '@genesis/shared';
import fs from 'fs';
import path from 'path';

async function run() {
  console.log('--- T5.7 CLOSED-LOOP ECONOMIC VERIFICATION ---');
  
  console.log('[1] Bootstrapping Genesis Backend...');
  await persistenceService.bootstrap();
  
  // Disable background simulators that interfere with the test (e.g., 5000 random citizens)
  citizenService['simulator'].stop();
  
  console.log('\n[2] Setting up deterministic scenario...');
  
  await worldService.initialize();
  await environmentService.initialize();
  await resourceService.initialize();
  await spatialService.initialize();
  await citizenService.initialize();
  await decisionService.initialize();
  await perceptionService.initialize();
  await marketService.initialize();
  await financeService.initialize();
  await supplyService.initialize();
  await bankingService.initialize();
  
  console.log('\n[2] Setting up deterministic scenario...');
  
  const buildings = worldService.engine.buildingManager.getAllBuildings();
  const stores = buildings.filter(b => b.type === 'STORE' || (b as any).metadata?.type === 'STORE');
  const store = stores[0];
  if (!store) throw new Error('No store generated by world initialization');

  const citizens = citizenService.engine.listCitizens();
  let citizen = citizens.find(c => c.id === 'test-citizen-banking');
  if (!citizen) {
    citizen = {
      id: 'test-citizen-banking',
      name: 'Test Citizen',
      gender: CitizenGender.MALE,
      status: CitizenStatus.ACTIVE,
      birthDate: { year: -30, month: 1, day: 1, hour: 0, minute: 0, second: 0 },
      createdAtSim: { year: 1, month: 1, day: 1, hour: 0, minute: 0, second: 0 },
      locationId: 'some-location',
      vitalState: { hunger: 0, thirst: 0, energy: 100, health: 100, lastUpdatedSimulationTime: { year: 1, month: 1, day: 1, hour: 0, minute: 0, second: 0 } },
      personality: { priceSensitivity: 50, qualityPreference: 50, conveniencePreference: 50, planningTendency: 50, socialEngagement: 50, riskTolerance: 50, savingTendency: 50 },
      movementState: MovementState.IDLE,
      jobType: 'NONE'
    } as any;
    citizenService.engine['repository'].create(citizen!);
  }
  
  // Ensure citizen has a location
  citizen.locationId = store.id;
  
  // Create a workplace producer
  const workplaces = worldService.engine.workplaceRepository.findAll();
  let storeWorkplace = workplaces.find(w => w.type === 'SHOP' || w.type === 'STORE' || w.type === 'RETAIL');
  if (!storeWorkplace) {
     throw new Error('No SHOP or STORE workplace found! Cannot test commerce loop.');
  }

  if (!storeWorkplace.wallet) {
    storeWorkplace.wallet = {
      id: `wallet-${storeWorkplace.id}`,
      ownerId: storeWorkplace.id,
      balance: 0,
      totalIncome: 0,
      totalExpenses: 0,
      currency: 'GEN'
    };
  }
  const storeWallet = storeWorkplace.wallet!;
  storeWallet.balance = 5000; // Seed store with money

  // Seed citizen with money
  if (!citizen.wallet) {
    citizen.wallet = {
      id: `wallet-${citizen.id}`,
      ownerId: citizen.id,
      balance: 0,
      totalIncome: 0,
      totalExpenses: 0,
      currency: 'GEN'
    };
  }
  const citizenWallet = citizen.wallet!;
  citizenWallet.balance = 1000;

  // Let's seed store inventory with some food
  const storeInv = supplyService.inventoryManager.getInventory(storeWorkplace.inventoryId!);
  if (!storeInv) throw new Error('Store has no inventory');
  supplyService.inventoryManager.addItemQuantity(storeInv.id, 'food', 100, 'kg');

  console.log('\n[3] Taking Initial Snapshots...');
  const initialCitizenMoney = citizenWallet.balance;
  const initialStoreMoney = storeWallet.balance;
  const totalMoneyInitial = initialCitizenMoney + initialStoreMoney;
  
  const currentTimeSeconds = (citizenService.engine as any).timeEngine.getUptimeSeconds();
  const initialStoreFood = supplyService.inventoryManager.getUsableQuantity(storeInv.id, 'food', currentTimeSeconds);
  
  const ownerId = citizen.householdId || citizen.id;
  let citizenInv = supplyService.inventoryManager.getInventoryByOwner(ownerId);
  if (!citizenInv) {
    // Create household inventory in memory if it wasn't hydrated
    citizenInv = supplyService.inventoryManager.createInventory(`inv-${ownerId}`, ownerId, 100);
  }
  const initialCitizenFood = supplyService.inventoryManager.getUsableQuantity(citizenInv.id, 'food', currentTimeSeconds);
  const totalFoodInitial = initialStoreFood + initialCitizenFood;

  console.log(`Initial State:
  Citizen Money: ${initialCitizenMoney}
  Store Money: ${initialStoreMoney}
  TOTAL MONEY: ${totalMoneyInitial}
  
  Store Food: ${initialStoreFood} kg
  Citizen Food: ${initialCitizenFood} kg
  TOTAL FOOD: ${totalFoodInitial} kg`);

  console.log('\n[4] Executing Citizen Purchase Flow...');
  
  // We manually force a purchase action to trace the exact closed loop
  const purchaseAction = {
    id: 'test-purchase-action',
    type: ActionType.PURCHASE,
    state: ActionState.PENDING,
    priority: 10,
    target: { type: 'BUILDING', id: storeWorkplace.id }, // Target the store workplace as the seller
    metadata: { productId: 'food', targetQuantity: 10, selectedStoreId: storeWorkplace.id },
    createdAt: new Date() as any,
  };
  
  // Market Engine setup: ensure store workplace acts as seller
  // The PurchaseActionExecutor uses MarketEngine.processTransaction with sellerId = target.id
  // We need to ensure that the target is recognized as a workplace.
  // Actually, PurchaseActionExecutor might expect the seller to be the building OR the workplace.
  
  // Instead of relying on ActionExecutor (which might run asynchronous routing), we will invoke MarketEngine directly to prove commerce loop,
  // then invoke ActionExecutor tick for consumption loop.
  // Wait! The user requested to trace through ActionExecutor. Let's trace it.
  
  // To avoid routing delays, place citizen directly at the store workplace
  citizen.locationId = storeWorkplace.id;
  citizen.movementState = MovementState.IDLE;
  
  // Insert citizen into SQLite so it doesn't crash on persistence
  await prisma.citizen.upsert({
    where: { id: citizen.id },
    create: {
      id: citizen.id,
      name: citizen.name,
      gender: citizen.gender,
      status: citizen.status,
      birthDateJson: JSON.stringify(citizen.birthDate),
      createdAtSimJson: JSON.stringify(citizen.createdAt || { year: 1, month: 1, day: 1, hour: 0, minute: 0, second: 0 }),
      locationId: citizen.locationId,
      vitalStateJson: JSON.stringify(citizen.vitalState),
      personalityJson: JSON.stringify(citizen.personality),
      movementState: citizen.movementState,
      skillsJson: "{}",
      activeRouteJson: "null",
      jobScheduleJson: "null",
      employmentRecJson: "null",
      employmentStatus: "UNEMPLOYED"
    },
    update: {}
  });

  // Insert World into SQLite
  await prisma.world.upsert({
    where: { id: "dummy-world-id" },
    create: {
      id: "dummy-world-id",
      name: "Dummy World",
      description: "Dummy World for T5.7",
      randomSeed: 42,
      creationTime: 0,
      worldSize: 100,
      climateProfile: "Temperate",
      timeZone: "UTC",
      version: "1.0.0",
      status: "ACTIVE"
    },
    update: {}
  });

  // Insert Region into SQLite
  await prisma.region.upsert({
    where: { id: "region-dummy" },
    create: {
      id: "region-dummy",
      name: "Dummy Region",
      climate: "Temperate",
      population: 0,
      worldId: "dummy-world-id",
      description: "Dummy region",
      coordX: 0,
      coordY: 0
    },
    update: {}
  });

  await prisma.workplace.upsert({
    where: { id: storeWorkplace.id },
    create: {
      id: storeWorkplace.id,
      type: storeWorkplace.type,
      locationId: storeWorkplace.locationId || "loc-dummy",
      regionId: "region-dummy",
      capacity: storeWorkplace.capacity || 50,
      occupiedPositions: storeWorkplace.occupiedPositions || 0,
      vacancies: storeWorkplace.vacancies || 50,
      inventoryId: storeWorkplace.inventoryId || "inv-dummy",
      storageCapacity: storeWorkplace.storageCapacity || 1000,
      walletId: storeWorkplace.walletId || "wallet-dummy",
      revenue: storeWorkplace.revenue || 0,
      expenses: storeWorkplace.expenses || 0,
      profit: storeWorkplace.profit || 0,
      accountingHistoryJson: "[]",
      inventoryConfigJson: "{}",
      metadataJson: "{}"
    },
    update: {}
  });

  // Insert Wallets into SQLite so syncWallet can update them
  if (citizen.wallet) {
    await prisma.wallet.upsert({
      where: { id: citizen.wallet.id },
      create: {
        id: citizen.wallet.id,
        ownerId: citizen.id,
        balance: citizen.wallet.balance,
        currency: citizen.wallet.currency,
        totalIncome: citizen.wallet.totalIncome,
        totalExpenses: citizen.wallet.totalExpenses
      },
      update: {}
    });
  }

  if (storeWorkplace.wallet?.id) {
    const sWallet = storeWorkplace.wallet;
    await prisma.wallet.upsert({
      where: { id: sWallet.id },
      create: {
        id: sWallet.id,
        ownerId: storeWorkplace.id,
        balance: sWallet.balance || 5000,
        currency: sWallet.currency || 'CR',
        totalIncome: sWallet.totalIncome || 0,
        totalExpenses: sWallet.totalExpenses || 0
      },
      update: {}
    });
  }

  // Setup missing executors which are normally configured by App integration layer
  const { StoreRanker } = require('../packages/engine/src/decision/scoring/StoreRanker');
  const storeRanker = new StoreRanker(marketService.engine, supplyService.inventoryManager);
  
  citizenService.engine.actionExecutor.setMarketEngine(
    marketService.engine,
    storeRanker,
    spatialService.engine.queryService
  );
  
  const { ConsumptionEngine } = require('../packages/engine/src/consumption/ConsumptionEngine');
  
  // Seed commodity for consumption engine
  supplyService.productionEngine.commodities.set('food', {
    id: 'food',
    name: 'Food',
    category: 'CONSUMABLE',
    basePrice: 10,
    consumable: {
      restorationNeed: 'HUNGER',
      restorationValue: 10
    }
  } as any);


  citizenService.engine.actionExecutor.executeAction(citizen, purchaseAction);
  
  // Tick it a few times to complete
  for (let i = 0; i < 5; i++) {
    citizenService.engine.actionExecutor.tick(citizen);
  }
  
  const currentPurchaseAction = citizen.currentAction!;
  if (currentPurchaseAction.state !== ActionState.COMPLETED) {
    console.error(`Purchase failed! State is: ${currentPurchaseAction.state}`);
  } else {
    console.log('Purchase Action Completed Successfully.');
    console.log('Citizen Wallet:', citizen.wallet);
    console.log('Store Wallet:', storeWorkplace.wallet);
  }
  
  console.log('\n[5] Executing Citizen Consumption Flow...');
  // Force hunger so consumption has a reason to happen (40 -> 20 = 20 needed = 2 units of 10)
  citizen.vitalState.hunger = 40;
  
  const consumeAction = {
    id: 'test-consume-action',
    type: ActionType.CONSUME_FOOD,
    state: ActionState.PENDING,
    priority: 10,
    target: { type: 'ITEM', id: 'food' },
    metadata: { productId: 'food', targetQuantity: 2 },
    createdAt: new Date() as any,
  };
  
  citizenService.engine.actionExecutor.executeAction(citizen, consumeAction);
  
  // Advance time by 35 minutes to ensure consumption completes (it takes 30 mins)
  timeService.engine.advance(35 * 60);
  
  for (let i = 0; i < 5; i++) {
    citizenService.engine.actionExecutor.tick(citizen);
  }

  const currentConsumeAction = citizen.currentAction!;
  if (currentConsumeAction.state !== ActionState.COMPLETED) {
    console.error(`Consumption failed! State is: ${currentConsumeAction.state}`);
  } else {
    console.log('Consumption Action Completed Successfully.');
  }

  console.log('\n[6] Taking Final Snapshots & Verifying Conservation...');
  const finalCitizenMoney = citizenWallet.balance;
  const finalStoreMoney = storeWallet.balance;
  const totalMoneyFinal = finalCitizenMoney + finalStoreMoney;
  
  const finalStoreFood = supplyService.inventoryManager.getUsableQuantity(storeInv.id, 'food', currentTimeSeconds);
  const finalCitizenFood = supplyService.inventoryManager.getUsableQuantity(citizenInv.id, 'food', currentTimeSeconds);
  const totalFoodFinal = finalStoreFood + finalCitizenFood;
  
  console.log('Final Citizen Inventory Object:', JSON.stringify(citizenInv, null, 2));

  console.log(`Final State:
  Citizen Money: ${finalCitizenMoney}
  Store Money: ${finalStoreMoney}
  TOTAL MONEY: ${totalMoneyFinal}
  
  Store Food: ${finalStoreFood} kg
  Citizen Food: ${finalCitizenFood} kg
  TOTAL FOOD: ${totalFoodFinal} kg`);

  // Verify
  const moneyConservation = totalMoneyInitial === totalMoneyFinal;
  // Food conservation: initial food minus consumed (2 kg) should equal final food
  const expectedFinalFood = totalFoodInitial - 2;
  const foodConservation = totalFoodFinal === expectedFinalFood;

  console.log(`Money Conservation: ${moneyConservation ? 'PASS' : 'FAIL'} (${totalMoneyInitial} -> ${totalMoneyFinal})`);
  console.log(`Food Conservation: ${foodConservation ? 'PASS' : 'FAIL'} (${totalFoodInitial} - 2 consumed = ${totalFoodFinal})`);

  console.log('\n[7] Persisting State to SQLite...');
  const dirtyCollections = {
    citizens: new Set([citizen.id]),
    workplaces: new Set([storeWorkplace.id]) // Not technically tracked by persistence.service.ts dirty collections but we iterate all workplaces anyway
  };

  await persistenceService.persistTickBoundary(dirtyCollections);
  
  // Verify in SQLite directly
  const dbCitizenWallet = await prisma.wallet.findUnique({ where: { ownerId: citizen.id } });
  const dbStoreWallet = await prisma.wallet.findUnique({ where: { ownerId: storeWorkplace.id } });
  console.log(`SQLite Citizen Wallet: ${dbCitizenWallet?.balance}`);
  console.log(`SQLite Store Wallet: ${dbStoreWallet?.balance}`);

  const stateOutput = {
    citizenId: citizen.id,
    storeId: storeWorkplace.id,
    totalMoneyFinal,
    totalFoodFinal,
    finalCitizenMoney,
    finalStoreMoney,
    finalCitizenFood,
    finalStoreFood
  };

  fs.writeFileSync(path.join(__dirname, 't5_7_state.json'), JSON.stringify(stateOutput, null, 2));

  console.log('\n✅ Phase 1 Verification Script Complete. State saved for restart test.');
  await prisma.$disconnect();
}

run().catch(err => {
  console.error(err);
  prisma.$disconnect();
  process.exit(1);
});
